name: build and publish

on:
  push:
    tags:        # Trigger when new tags are pushed
      - 'v*.*.*'
env:
  REGISTRY: ghcr.io/yoyrandao

jobs:
  build:
    name: build images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - telegram-bot
          - notification-scheduler
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract Git Tag
        id: get-tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/${{ matrix.service }}/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/todoist-${{ matrix.service }}:${{ env.tag }}
            ${{ env.REGISTRY }}/todoist-${{ matrix.service }}:latest